import streamlit as st
import pandas as pd
import joblib

st.set_page_config(
    page_title="African Life Expectancy Predictor",
    page_icon="🌍",
    layout="centered"
)

MODEL_PATH = "models/life_expectancy_model.pkl"

model = joblib.load(MODEL_PATH)

features = [
    "GDP per Capita",
    "Health Expenditure",
    "Physicians",
    "Electricity Access",
    "School Enrollment",
    "Unemployment",
    "Population",
    "Basic Sanitation",
    "Year"
]

st.title("🌍 African Life Expectancy Predictor")

st.write(
    """
    This application predicts life expectancy using socioeconomic,
    health, education, infrastructure, population and temporal
    indicators from the World Bank World Development Indicators dataset.
    """
)

st.sidebar.header("Input Indicators")

gdp = st.sidebar.number_input(
    "GDP per Capita (US$)",
    min_value=0.0,
    value=2000.0
)

health_expenditure = st.sidebar.number_input(
    "Health Expenditure (% of GDP)",
    min_value=0.0,
    value=5.0
)

physicians = st.sidebar.number_input(
    "Physicians (per 1,000 people)",
    min_value=0.0,
    value=1.0
)

electricity = st.sidebar.number_input(
    "Electricity Access (%)",
    min_value=0.0,
    max_value=100.0,
    value=70.0
)

school_enrollment = st.sidebar.number_input(
    "Secondary School Enrollment (%)",
    min_value=0.0,
    value=60.0
)

unemployment = st.sidebar.number_input(
    "Unemployment (%)",
    min_value=0.0,
    value=10.0
)

population = st.sidebar.number_input(
    "Population",
    min_value=0.0,
    value=10000000.0
)

sanitation = st.sidebar.number_input(
    "Basic Sanitation Access (%)",
    min_value=0.0,
    max_value=100.0,
    value=60.0
)

year = st.sidebar.number_input(
    "Year",
    min_value=2000,
    max_value=2025,
    value=2025
)

input_data = pd.DataFrame([{
    "GDP per Capita": gdp,
    "Health Expenditure": health_expenditure,
    "Physicians": physicians,
    "Electricity Access": electricity,
    "School Enrollment": school_enrollment,
    "Unemployment": unemployment,
    "Population": population,
    "Basic Sanitation": sanitation,
    "Year": year
}])

st.subheader("Prediction Inputs")

st.dataframe(input_data, use_container_width=True)

if st.button("Predict Life Expectancy", type="primary"):

    prediction = model.predict(input_data)[0]

    st.success(
        f"Predicted Life Expectancy: {prediction:.2f} years"
    )

    st.info(
        "This prediction is generated by a Random Forest regression model "
        "trained on World Bank World Development Indicators."
    )